<h2>Sign up using this form</h2>

<?php echo $this->tag->form("secure/adduser"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
   
    <p>
        <label for="role">Role</label>
        <?php echo $this->tag->textField("role"); ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

</form>